### ISSUE TITLE
Tilda LCD in Arduino mode in 2020

### ISSUE THREAD

**Issue by wu-lee** [emfcamp/Mk2-Firmware#127]
Hello! I still have a Tilda Mke, which I've started to hack on 6 years late (we need a thermostat). Seems a shame to waste it.

I'm treating it as an Arduino Due, for simplicity. I've found it won't compile against the latest Arduino core (I'm using the v1.8.12 Ubuntu snap package), but I've managed to fix the initial problems (which require adding a second buffer parameter to the UARTClass and USARTClass definitions). 

- Can I drop in the latest Arduino core library from [here][core]?

[core]: https://github.com/arduino/ArduinoCore-sam/tree/master/cores/arduino

But I'm having trouble getting any of the [u8g2][] LCD library examples to work. I can get them to compile and upload, and run (because I can write serial, flash LEDs, and even light the backlight). However the screen remains blank, even if I change the offset in case the text is offscreen.

[u8g2]: https://github.com/olikraus/u8g2/

I think this library didn't even exist when the Mke was built.

- Should I expect this to work, or is it a bridge too far?
- Will the constructor in the [example][helloworldcons] work?

[helloworldcons]: https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8x8/HelloWorld/HelloWorld.ino#L125

This constructor is:

    U8X8_KS0108_128X64 u8x8(8, 9, 10, 11, 4, 5, 6, 7, /*enable=*/ 18, /*dc=*/ 17, /*cs0=*/ 14, /*cs1=*/ 15, /*cs2=*/ U8X8_PIN_NONE, /* reset=*/  U8X8_PIN_NONE); 	// Set R/W to low!

I've attempted to revert to a version of Arduino IDE from around the time of EMF Camp 2014, 1.5.7, but obviously I can't revert u8g2 that far, and in fact the library seems not to use the layout 1.5.7 expects, so now wondering how far I can get with this board and this library. I'm wondering if there is some mismatch between the Arduino IDE now and the Tilda Mke then: pin definitions got awry, etc.

Can anyone can remember this far back? I'd be grateful for any pointers to code I can study to try and get this working in arduino mode. The Mk2-Firmware repo seems to be all RTOS based, and to use something called [M2tklib][] which looks a bit abandoned.

[M2tklib]: https://github.com/olikraus/m2tklib

**Comment by dpslwk** [comment]
first thing I spot is the display is a ST7565 based not KS0108
https://github.com/emfcamp/Mk2-Documentation/tree/master/LCD%20JHD12864

so may well be the wrong constructor for u8g2

GLCD was the display driver used back then IIRC
https://github.com/emfcamp/Mk2-Firmware/tree/master/hardware/emfcamp/sam/libraries/GLCD

**Comment by wu-lee** [comment]
Ah, thanks! Well that may be it. I got my information that it's KS0108-based here:

https://www.geeetech.com/wiki/index.php/Graphic_LCD_128x64_STN_LED

> JHD12864E is a 128X64 graphical LCD with backlight. This unit is a very clear STN type LCD with a simple command interface. Utilizes the extremely common KS0108B parallel interface chipset. Interface code is freely available.

However, a bit more googling finds this:

https://blog.arcanium.london/2019/05/resurrecting-tilda-mke-part-2.html?m=0

**Comment by wu-lee** [comment]
Thanks, to summarise, u8g2 works:
- You are correct, the display is ST7565
- The arcanium blog post's sketch works

Therefore marking this closed.

I have been having other problems which delayed this answer, specifically I'm finding that the arcanium sketch wouldn't compile correctly because of errors linking `syscalls_sam3.c.o`, and I've only worked around this by hunting down and disabling the caching for the core library in `preferences.txt`. I had two sketches, one which worked (a version of u8g2's Hello World) and one which didn't (the arcanium sketch) which persisted despite incrementally converging them to the same code.

Also, I have patched the core library to allow it to compile, but I will need to submit that in a separate issue.

Anyway, that aside, the constructor which works is this:
```
#define LCD_CS          BOARD_SPI_SS2
#define LCD_POWER       (40u)
#define LCD_A0            (38u)
#define LCD_RESET         (34u)
#define CMD_SET_BIAS_9 0xA2
#define CMD_SET_BIAS_7 0xA3

//Screen is JHD12864-G13BSW and ST7565 controller
U8G2_ST7565_ERC12864_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ LCD_CS, /* dc=*/ LCD_A0, /* reset=*/ LCD_RESET); // - Works well!
```

And the arcanium post sets the bias and contrast like this in `setup`:
```
  //Set the bias so it's legible
  u8x8_cad_StartTransfer(u8g2.getU8x8());
  u8x8_cad_SendCmd(u8g2.getU8x8(), CMD_SET_BIAS_9);
  u8x8_cad_EndTransfer(u8g2.getU8x8());
  
  //Set some contrast now the bias is OK
  u8g2.setContrast(32);
```

It also sets the contrast as above, before rendering text in `loop`.
